apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-disk
  namespace: vm-import-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
