apiVersion: v1
kind: Pod
metadata:
  name: test-pod-macvlan
  namespace: vm-multihoming
  annotations:
    k8s.v1.cni.cncf.io/networks: default/macvlan-network
spec:
  containers:
  - name: test-container
    image: registry.access.redhat.com/ubi8/ubi:latest
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
