apiVersion: v1
kind: Service
metadata:
  name: lab-vm-rdp-service
  namespace: default
spec:
  selector:
    vm.kubevirt.io/name: lab-vm-console
  ports:
  - name: rdp
    port: 3389
    targetPort: 3389
    protocol: TCP
  type: ClusterIP
