apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: always-run-vm
  namespace: vm-lifecycle-lab
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: always-run-vm
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
