# vm-admin-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vm-security-lab
  name: vm-admin
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["*"]
  verbs: ["*"]
