apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-disk-pvc
  namespace: default
  labels:
    app: vm-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "" # Use default storage class
