apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-pvc
  namespace: default
  labels:
    app: vm-data-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Use default storage class
