apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: resource-test-vm
  labels:
    app: resource-test
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: resource-test-vm
    spec:
      domain:
        cpu:
          cores: 2
          threads: 2
          sockets: 1
        memory:
          guest: 1Gi
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: 2
          limits:
            memory: 1Gi
            cpu: 2
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
      - name: cloudinitdisk
        cloudInitNoCloud:
          userDataBase64: SGkuXG4=
